### ISSUE TITLE
Support for default image if an OG/Meta image is not available

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/bookmark-action#136]
Would it be possible to use a default/placeholder image for articles/links that are added and do not have an image associated with the post to avoid a broken image when displaying in my template?

**Comment by katydecorah** [comment]
@flamedfury Is it possible to add logic to your site to catch if a bookmark doesn't have an image and then show a different image? If so, this may afford you greater flexibility than hardcoding a placeholder image into the dataset.

Here's an example:

```liquid
{% for bookmark in bookmarks %}
<img src="{% if bookmark.image %}{{bookmark.image}}{% else %}placeholder.png{% endif %}" alt="{{bookmark.title}}" />
{% endfor %}
```

**Comment by flamedfury** [comment]
Thanks for the tip @katydecorah I'll check this out and report back.

**Comment by flamedfury** [comment]
I think that the issue I run into is that the seasonal post frontmatter yaml adds the image into the frontmatter, whether it exists or not in the metadata-library...

e.g. 2023-03-20-2023-summer.md
```yaml
bookmarks:
  - title: 2023, the year of websites
    site: Andy Bell
    url: https://andy-bell.co.uk/2023-the-year-of-websites/
    image: bookmark-2023-the-year-of-websites.jpg
```

If you check the `img` directory in the repo that image doesn't exist, https://github.com/flamedfury/metadata-library/tree/main/img

It also shows it exists in the json file too https://github.com/flamedfury/metadata-library/blob/0be0c56d761fa92984eb7d0b0a53b6507b4739a2/_data/bookmarks.json#LL20C18-L20C18

Does this make sense? Or has my action bugged out?
