### ISSUE TITLE
URL sometimes not saved to yaml

### ISSUE THREAD

**Issue by joshghent** [katydecorah/bookmark-action#62]
Hey @katydecorah, thanks for an awesome project.

For some reason I have found that this website: https://thefullstackdev.net/article/create-beautiful-website-while-sucking-at-design/ doesn't appear to download correctly.

It generated the following yaml
```yaml
- title: You can create a great looking website while sucking at design
  site: ''
  date: '2022-08-03'
  description: How to create great looking websites while having little design skill.
  image: ''
  type: ''
  notes: "blah blah blah"
```

As you can see it didn't grab the URL correctly for some reason.
Thought I would just report this to you :)

Thanks for a great project!
